#!/usr/bin/env bash

#/ command: syslog-ng:service: "Ensure container startup is managed by systemd"
#/ usage: rerun syslog-ng:service  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --requires <>]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER REQUIRES

. "$RERUN_MODULE_DIR/lib/functions.sh" "service" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail -o errtrace

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
. "$RERUN_MODULES/lib/print.sh"
. "$RERUN_MODULES/lib/systemd.sh"
THIS="$RERUN_MODULE_DIR/commands/service"
SVC="podman:syslog-ng.service"
PRINT "+" "Stopping existing unit..."
unit_stop "$SVC"
PRINT "+" "Generating systemd unit..."
unit_install "$THIS/$SVC"
unit_image "$ARG" "$SVC"
PRINT "+" "Enabling and starting service..."
unit_start "$SVC"
PRINT "+" "Checking if container service is up..."
unit_active "$SVC"
PRINT "!" "DONE."
exit 112
