#!/usr/bin/env bash

#/ command: promtail:create: "Create container image"
#/ usage: rerun promtail:create  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --requires <>] [ --loki <localhost>] [ --binary <./promtail>]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER REQUIRES LOKI BINARY

. "$RERUN_MODULE_DIR/lib/functions.sh" "create" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail -o errtrace

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
THIS="$RERUN_MODULE_DIR/commands/create"
export NAME="promtail-build"
export FROM="docker://docker.io/library/debian:unstable-slim"
export OPTS=""
. "$RERUN_MODULES/lib/buildah.sh"
. "$RERUN_MODULES/lib/print.sh"
[ -x "$BINARY" ] || { >&2 PRINT "!!" "Missing promtail executable. Please compile your own."; exit 1; }
APT_GET="/usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get -qq"
MKDIR /usr/share/man/man1
MKDIR /usr/share/man/man7
RUN /usr/bin/touch /usr/share/man/man1/sh.distrib.1.gz
RUN cp --remove-destination /usr/share/zoneinfo/UTC /etc/localtime
RUN $APT_GET update
RUN $APT_GET dist-upgrade
RUN /usr/bin/find {/bin,/sbin,/usr/bin,/usr/sbin} -type f -exec chmod u-s {} +
CLEAR /tmp
CLEAR /var/tmp
CLEAR /var/cache
CLEAR /var/log
CLEAR /var/lib/apt/lists
CLEAR /usr/share/man
CLEAR /usr/share/common-licenses
CLEAR /usr/share/doc
RUN $APT_GET --allow-remove-essential remove sysvinit-utils e2fsprogs e2fslibs tzdata findutils dmeventd
RUN $APT_GET autoremove
RUN $APT_GET clean
RUN useradd -M -N -u 65522 -s /sbin/nologin promtail
COPY "$THIS/promtail.yaml" /
RUN sed -i "s|__LOKI__|$LOKI|" "/promtail.yaml"
COPY "$BINARY" /
ENTRYPOINT '["/promtail", "-config.file=/promtail.yaml"]'
COMMIT "$ARG"
exit 112
