#!/usr/bin/env bash

#/ command: promtail:create: "Create container image"
#/ usage: rerun promtail:create  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --requires <>] [ --loki <localhost>] [ --binary <./promtail>]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER REQUIRES LOKI BINARY

. "$RERUN_MODULE_DIR/lib/functions.sh" "create" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail -o errtrace

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
THIS="$RERUN_MODULE_DIR/commands/create"
export NAME="promtail-build"
export FROM="scratch"
export OPTS=""
. "$RERUN_MODULES/lib/buildah.sh"
. "$RERUN_MODULES/lib/print.sh"
[ -x "$BINARY" ] || { >&2 PRINT "!!" "Missing promtail executable. Please compile your own."; exit 1; }
sed "s|__LOKI__|$LOKI|" "$THIS/promtail.yaml" > "$THIS/promtail.yaml.new"
COPY "$THIS/promtail.yaml.new" /promtail.yaml
COPY "$THIS/passwd" /etc/passwd
COPY "$THIS/group" /etc/group
rm -f "$THIS/promtail.yaml.new"
COPY "$BINARY" /
MKDIR /tmp
ENTRYPOINT '["/promtail", "-config.file=/promtail.yaml"]'
COMMIT "$ARG"
exit 112
