#!bin/lua
package.path="vendor/lua/?.lua"
local T = require "u-test"
local exec = require "exec"
local cmd = exec.cmd
local tests = {
  "Lua",
  "lua-module-exec",
  "lua-module-lib",
  "configi-basic-functionality",
}
T["Configi Tests"] = function()
  for _, t in ipairs(tests) do
    T[t] = function()
      local a, b = cmd["bin/lua"]("tests/"..t..".lua")
      T.is_number(a)
      T.equal(b.code, 0)
    end
  end
end
