#!bin/lua
package.path="vendor/lua/?.lua"
local T = require "u-test"
local exec = require "exec"
local luacheck = exec.ctx"bin/luacheck.lua"
local cmd = exec.cmd
local tests = {
  "Lua",
  "lua-module-exec",
  "lua-module-lib",
  "configi-basic-functionality",
}
T["Configi Tests"] = function()
  T["$ luacheck bin/cfg.lua"] = function()
    local a, b = luacheck("--max-code-line-length", "160", "bin/cfg.lua")
    T.equal(b.code, 0)
  end
  for _, t in ipairs(tests) do
    T["$ bin/lua tests/"..t..".lua"] = function()
      local a, b = cmd["bin/lua"]("tests/"..t..".lua")
      T.is_number(a)
      T.equal(b.code, 0)
    end
  end
end
