#!/usr/bin/env bash

#/ command: image:push: "Push container image to remote rsync registry via SSH"
#/ usage: rerun image:push  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --requires <>]  --host <> [ --tag <latest>]  --dest <> [ --unsigned <false>]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER REQUIRES HOST TAG DEST UNSIGNED

. "$RERUN_MODULE_DIR/lib/functions.sh" "push" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

unset HOST
set -o errexit -o nounset -o pipefail -o errtrace

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
# Requires skopeo, tar, xz, openssh(scp), coreutils(sha256sum), opmsg
#
. "$RERUN_MODULES/lib/functions.sh"
TMPDIR=$(mktemp -d -p .)
1>/dev/null pushd "${TMPDIR}"
    /usr/bin/mkdir "${DEST}"
    print "Converting local image to oci-archive..."
    /usr/bin/skopeo copy "containers-storage:${ARG}" "oci-archive:${DEST}/${TAG}"
    print "Compressing image before pushing..."
    /usr/bin/sha256sum "${DEST}/${TAG}" > "${DEST}/${TAG}.sha256"
    if [ "$UNSIGNED != "true" ]
    then
        print "Please sign the following (single line only)..."
        cat "${DEST}/${TAG}.sha256"
        print "Input the signature here. CTRL-D to mark the end:"
        SIG=$(</dev/stdin)
        printf '%s' "$SIG" > "${DEST}/${TAG}.sign"
    fi
    XZ_OPT=-T0 /usr/bin/tar -cJf IMAGE.tar.xz "${DEST}"
    print "Pushing to rsync registry..."
    if [ "$HOST" = "localhost" ]
    then
        /usr/bin/install -p -D -g 13873 -o 13873 IMAGE.tar.xz "/srv/rsyncd/registry/${DEST}/$TAG"
    else
        /usr/bin/scp IMAGE.tar.xz "root@${HOST}:/srv/rsyncd/registry/${DEST}/${TAG}"
    fi
1>/dev/null popd
rm -r "${TMPDIR}/${DEST}"
rm -f "${TMPDIR}/IMAGE.tar.xz"
rmdir "${TMPDIR}"
print "Done!"
exit 112
