#!/usr/bin/env bash

#/ command: cfg:fedora: "Create Fedora Linux container"
#/ usage: rerun cfg:fedora  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --requires <>]  --version <>  --manifest <>  --modules <> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER REQUIRES VERSION MANIFEST MODULES

. "$RERUN_MODULE_DIR/lib/functions.sh" "fedora" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

# Done. Exit with last command exit status.
exit $?

