#!/usr/bin/env bash

#/ command: mariadb:service: "Ensure podman-mariadb is a systemd managed service"
#/ usage: rerun mariadb:service  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --requires <>]  --mariadb <> 
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER REQUIRES MARIADB

. "$RERUN_MODULE_DIR/lib/functions.sh" "service" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
function cleanup() {
    PRINT "+" "Deleting incomplete systemd unit..."
    rm -f "$SERVICE"
    systemctl daemon-reload
}
trap cleanup ERR
systemctl is-active "podman:mariadb-$MARIADB" && exit 0
. "$RERUN_MODULES/lib/print.sh"
PRINT "+" "Getting image ID of MariaDB $MARIADB container..."
IMAGE=$(podman images | grep -F "mariadb-$MARIADB" | awk '{print $3}')
SERVICE="/etc/systemd/system/podman:mariadb-$MARIADB.service
PRINT "+" "Generating systemd unit..."
cp "$RERUN_MODULE_DIR/commands/service/podman:mariadb.service" $SERVICE
sed -i "s:__IMAGE__:$IMAGE:g" $SERVICE
sed -i "s:__MARIADB__:$MARIADB:g" $SERVICE
PRINT "+" "Enabling and starting MariaDB container service..."
systemctl daemon-reload
systemctl enable "podman:mariadb-$MARIADB"
systemctl start "podman:mariadb-$MARIADB"
PRINT "+" "Checking if MariaDB container service is up..."
systemctl is-active "podman:mariadb-$MARIADB"
PRINT "!" "DONE."
exit 113
# Done. Exit with last command exit status.
exit $?

