#!/usr/bin/env bash

#/ command: postgresql:useradd: "Add PostgreSQL user"
#/ usage: rerun postgresql:useradd  --arg <> [ --comment <>] [ --verbose <>] [ --register <>]  --postgresql <>  --address <>  --database <>  --password <>
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER POSTGRESQL ADDRESS DATABASE PASSWORD

. "$RERUN_MODULE_DIR/lib/functions.sh" "useradd" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
. "$RERUN_MODULES/lib/print.sh"
PRINT "+H" "Checking if PostgreSQL container service is active..."
systemctl is-active "podman-postgresql-$POSTGRESQL"
PRINT "+C" "Creating PostgreSQL user $ARG..."
podman exec -it "postgresql-$POSTGRESQL" runuser postgres -c "createuser -d -S $ARG"
printf \"ALTER USER %s WITH ENCRYPTED PASSWORD \'%s\';\n\" $ARG $PASSWORD | podman exec -it "postgresql-$POSTGRESQL" runuser postgres -c psql
PRINT "+H" "Adding pg_hba.conf entry for $ARG..."
echo "host $DATABASE $ARG $ADDRESS md5" >> "/srv/postgresql-$POSTGRESQL/conf/pg_hba.conf"
PRINT "!" "Done."
# Done. Exit with last command exit status.
exit $?

