#!/usr/bin/env bash

#/ command: configi:setup-command: "Add and setup command in Configi module"
#/ usage: rerun configi:setup-command  --module <>  --command <>  --desc <>
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: MODULE COMMAND DESC

. "$RERUN_MODULE_DIR/lib/functions.sh" "setup-command" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
RERUN_MODULES=./modules rerun stubbs:add-command --module "$MODULE" --command "$COMMAND" --description "$DESC"
RERUN_MODULES=./modules rerun stubbs:add-option --option arg --description "Configi: main argument" --module "$MODULE" --command "$COMMAND" --required true --export false
RERUN_MODULES=./modules rerun stubbs:add-option --option comment --description "Configi: comments" --module "$MODULE" --command "$COMMAND" --required false --export false
RERUN_MODULES=./modules rerun stubbs:add-option --option verbose --description "Configi: verbosity" --module "$MODULE" --command "$COMMAND" --required false --export false
RERUN_MODULES=./modules rerun stubbs:add-option --option register --description "Configi: register variable" --module "$MODULE" --command "$COMMAND" --required false --export false
RERUN_MODULES=./modules rerun stubbs:add-option --option requires --description "Configi: requires variable" --module "$MODULE" --command "$COMMAND" --required false --export false
# Done. Exit with last command exit status.
exit $?

