# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Wed Dec 26 05:12:07 UTC 2018
#
#/ usage: configi:setup-command  --module <>  --command <>  --desc <> 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
#
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
  
    unrecognized_args=()

    while (( "$#" > 0 ))
    do
        OPT="$1"
        case "$OPT" in
            --module) rerun_option_check $# $1; MODULE=$2 ; shift 2 ;;
            --command) rerun_option_check $# $1; COMMAND=$2 ; shift 2 ;;
            --desc) rerun_option_check $# $1; DESC=$2 ; shift 2 ;;
            # help option
            -\?|--help)
                rerun_option_usage
                exit 2
                ;;
            # unrecognized arguments
            *)
              unrecognized_args+=("$OPT")
              shift
              ;;
        esac
    done

    # Set defaultable options.

    # Check required options are set
    [[ -z "$MODULE" ]] && { echo >&2 "missing required option: --module" ; return 2 ; }
    [[ -z "$COMMAND" ]] && { echo >&2 "missing required option: --command" ; return 2 ; }
    [[ -z "$DESC" ]] && { echo >&2 "missing required option: --desc" ; return 2 ; }
    # If option variables are declared exportable, export them.

    # Make unrecognized command line options available in $_CMD_LINE
    if [ ${#unrecognized_args[@]} -gt 0 ]; then
      export _CMD_LINE="${unrecognized_args[@]}"
    fi
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${MODULE:=}
: ${COMMAND:=}
: ${DESC:=}
# Default command line to null if not set
: ${_CMD_LINE:=}


