#!/usr/bin/env bash

#/ command: buildah:copy: "Copies the contents of a file, URL, or directory into a container's working directory"
#/ usage: rerun buildah:copy  --arg <> [ --comment <>] [ --verbose <>] [ --register <>]  --src <>  --dest <> [ --chown <>]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER SRC DEST CHOWN

. "$RERUN_MODULE_DIR/lib/functions.sh" "copy" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
if [ -z "$CHOWN" ]
then
    buildah copy "$ARG" "$SRC" "$DEST" && exit 112
else
    buildah copy --chown "$CHOWN" "$ARG" "$SRC" "$DEST" && exit 112
fi
# Done. Exit with last command exit status.
exit $?

