#!/usr/bin/env bash

#/ command: buildah:mkdir: "Create a directory inside the container"
#/ usage: rerun buildah:mkdir  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --directory <>]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER DIRECTORY

. "$RERUN_MODULE_DIR/lib/functions.sh" "mkdir" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
buildah run "$ARG" -- mkdir -p "$DIRECTORY" && exit 112
# Done. Exit with last command exit status.
exit $?

