#!/usr/bin/env bash

#/ command: buildah:sh: "Use subshell for running a command"
#/ usage: rerun buildah:sh  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --options <>] [ --command <>]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER OPTIONS COMMAND

. "$RERUN_MODULE_DIR/lib/functions.sh" "sh" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
buildah run $OPTIONS "$ARG" -- sh -l -c "$COMMAND" && exit 112
# Done. Exit with last command exit status.
exit $?

