#!/usr/bin/env bash

#/ command: zerotier:create: "Create ZeroTier container"
#/ usage: rerun zerotier:create  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --network <>] [ --planet <>] [ --moons <>] [ --requires <>] [ --public <>] [ --secret <>]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER NETWORK PLANET MOONS REQUIRES PUBLIC SECRET

. "$RERUN_MODULE_DIR/lib/functions.sh" "create" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail -o errtrace

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
function cleanup {
    PRINT "+H" "Abort. Cleaning up..."
    buildah rm $NAME
    PRINT "+X" "Error encountered!"
}
trap cleanup ERR
NAME="zerotier-build"
FROM="debian:stretch-slim"
BIND="/srv/zerotier"
OPTS="-v $BIND:/var/lib/zerotier-one"
mkdir -p /srv/zerotier
. "$RERUN_MODULES/lib/print.sh"
PRINT "+H" "Pulling source image ($FROM)..."
. "$RERUN_MODULES/lib/buildah.sh"
APT_GET="/usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get -qq"
MKDIR /usr/share/man/man1
MKDIR /usr/share/man/man7
RUN /usr/bin/touch /usr/share/man/man1/sh.distrib.1.gz
RUN cp --remove-destination /usr/share/zoneinfo/UTC /etc/localtime
RUN $APT_GET update
RUN $APT_GET dist-upgrade
RUN $APT_GET --no-install-recommends install curl gnupg dirmngr ca-certificates
SH "curl -Lo - https://www.zerotier.com/misc/contact@zerotier.com.gpg | apt-key add -"
SH "echo 'deb http://download.zerotier.com/debian/stretch stretch main' > /etc/apt/sources.list.d/zerotier.list"
RUN $APT_GET update
RUN $APT_GET install zerotier-one=1.2.12
RUN $APT_GET remove curl gnupg dirmngr ca-certificates
RUN $APT_GET --allow-remove-essential remove sysvinit-utils e2fsprogs e2fslibs tzdata
RUN $APT_GET autoremove
RUN $APT_GET clean
MKDIR /var/lib/zerotier-one/networks.d
RUN touch "/var/lib/zerotier-one/networks.d/$NETWORK.conf"
printf "{\n\t\"settings\":\n\t{\n\t\t\"allowTcpFallbackRelay\": false\n\t}\n}\n" > "$BIND/local.conf"
if [ -f "$PLANET" ]
then
    cp "$PLANET" "$BIND/planet"
fi
if [ -d "$MOONS" ]
then
    cp -R "$MOONS" "$BIND"
fi
if [ -f "$PUBLIC" ]
then
    cp "$PUBLIC" "$BIND/identity.public"
fi
if [ -f "$SECRET" ]
then
    cp "$SECRET" "$BIND/identity.secret"
    chmod 0600 "$BIND/identity.secret"
fi
RUN chown -R zerotier-one:zerotier-one /var/lib/zerotier-one
CLEAR /tmp
CLEAR /var/tmp
CLEAR /var/cache
CLEAR /var/log
CLEAR /var/lib/apt/lists
CLEAR /usr/share/man
CLEAR /usr/share/common-licenses
CLEAR /usr/share/doc
CONFIG --entrypoint '["/usr/sbin/zerotier-one"]'
CONFIG --cmd ''
CONFIG --stop-signal TERM
if [ "$ARG" = "local" ]
then
    PRINT "+H" "Committing to containers-storage..."
    buildah commit --rm --squash "${NAME}" "containers-storage:zerotier"
else
    PRINT "+H" "Committing to containers-storage as $ARG..."
    buildah commit --rm --squash "${NAME}" "containers-storage:$ARG"
fi
exit 113
# Done. Exit with last command exit status.
exit $?
