#!/usr/bin/env bash

#/ command: image:pull: "Pull container image from remote rsync registry"
#/ usage: rerun image:pull  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --requires <>]  --host <>  --creds <>
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER REQUIRES HOST CREDS

. "$RERUN_MODULE_DIR/lib/functions.sh" "pull" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

unset HOST
set -o errexit -o nounset -o pipefail -o errtrace

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
. "$RERUN_MODULES/lib/functions.sh"
if [ ! -f "$CREDS" ]
then
    print "Missing credentials file."
fi
TMPDIR=$(mktemp -d -p .)
cp "$CREDS" "$TMPDIR/CREDS"
1>/dev/null pushd "$TMPDIR"
    NAME=$(cut -f1 -d:<<<"$ARG")
    TAG=$(cut -f2 -d:<<<"$ARG")
    LOGIN=$(cut -f1 -d: < ./CREDS)
    PASS=$(cut -f2 -d: < ./CREDS)
    printf '%s\n' "${PASS}" > ./PASS
    chmod 0600 ./PASS
    /usr/bin/rsync --password-file=./PASS --progress -h -W "${LOGIN}@${HOST}::${NAME}/${TAG}" ./IMAGE.tar.xz
    /usr/bin/tar -xJf IMAGE.tar.xz
    /usr/bin/sha256sum -c < "${NAME}/${TAG}.sha256"
    /usr/bin/skopeo copy "oci-archive:${NAME}/${TAG}" "containers-storage:${NAME}:${TAG}"
1>/dev/null popd
rm -rf "${TMPDIR}/${NAME}"
rm -f "${TMPDIR}/{IMAGE.tar.xz,PASS,CREDS}"
rmdir "${TMPDIR}"
exit 112
