#!/usr/bin/env bash

#/ command: mariadb:secure: "Run the equivalent of mysql_secure_installation"
#/ usage: rerun mariadb:secure  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --requires <>]  --password <>  --mariadb <>
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER REQUIRES PASSWORD MARIADB

. "$RERUN_MODULE_DIR/lib/functions.sh" "secure" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
FTEMP="/srv/mariadb-$MARIADB/data/.__temp"
. "$RERUN_MODULES/lib/print.sh"
RETRIES=5
until podman exec -it "mariadb-$MARIADB" runuser root -c "mysql -u root -e 'select 1'" > /dev/null 2>&1 || [ "$RETRIES" -eq 0 ]
do
    PRINT "+C" "Waiting for MariaDB $MARIADB to come up..."
    RETRIES=$((RETRIES-=1))
    sleep 1
done
cat > "$FTEMP" << QUERY
UPDATE mysql.user SET Password=PASSWORD('__PASSWORD__') WHERE User='root';
DELETE FROM mysql.user WHERE User='';
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
FLUSH PRIVILEGES;
QUERY
sed -i "s:__PASSWORD__:$PASSWORD:g" "$FTEMP"
PRINT "+C" "Running queries..."
podman exec -it "mariadb-$MARIADB" runuser root -c "mysql -sfu root < /data/.___temp"
rm -f "$FTEMP"
exit 113
# Done. Exit with last command exit status.
exit $?
