#!/usr/bin/env bash

#/ command: buildah:run: "Run a command inside of the container"
#/ usage: rerun buildah:run  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --options <>] [ --command <>]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER OPTIONS COMMAND

. "$RERUN_MODULE_DIR/lib/functions.sh" "run" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
buildah run $OPTIONS -- "$ARG" "$COMMAND" && exit 112
# Done. Exit with last command exit status.
exit $?

