#!/usr/bin/env bash

#/ command: loki:create: "Create container image"
#/ usage: rerun loki:create  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --requires <>]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER REQUIRES

. "$RERUN_MODULE_DIR/lib/functions.sh" "create" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail -o errtrace

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
THIS="$RERUN_MODULE_DIR/commands/create"
export NAME="loki-build"
export FROM="scratch"
export OPTS=""
. "$RERUN_MODULES/lib/buildah.sh"
. "$RERUN_MODULES/lib/print.sh"
[ -x "$THIS/loki" ] || { >&2 PRINT "!!" "Missing loki executable. Please compile your own."; exit 1 }
COPY "$THIS/loki.yaml" /
COPY "$THIS/loki" /
ENTRYPOINT '["/loki", "-config.file=/loki.yaml"]'
COMMIT "$ARG"
exit 112
