#!/usr/bin/env bash

#/ command: buildah:local: "commit container to local containers-storage"
#/ usage: rerun buildah:local  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --name <>]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER NAME

. "$RERUN_MODULE_DIR/lib/functions.sh" "local" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
buildah commit "$ARG" containers-storage:"$NAME" && exit 112
# Done. Exit with last command exit status.
exit $?

