#!/usr/bin/env bash

#/ command: configi:add-module: "Add new Configi module"
#/ usage: rerun configi:add-module  --module <>  --desc <>
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. "$RERUN_MODULE_DIR/lib/functions.sh" "add-module" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
RERUN_MODULES=./modules rerun stubbs:add-module --module "$MODULE" --description "$DESC"
# Done. Exit with last command exit status.
exit $?

