#!/usr/bin/env bash

#/ command: buildah:config: "Update image configuration settings"
#/ usage: rerun buildah:config  --arg <> [ --comment <>] [ --verbose <>] [ --register <>]  --options <>
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER OPTIONS

. "$RERUN_MODULE_DIR/lib/functions.sh" "config" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
buildah config "$OPTIONS" "$ARG" && exit 112
# Done. Exit with last command exit status.
exit $?

