#!/usr/bin/env bash

#/ command: zerotier:controller: "Create ZeroTier Moon #/ command: zerotier:controller: "Create ZeroTier Moon #/ command: zerotier:controller: "Create ZeroTier Moon #/ command: zerotier:controller: "Create ZeroTier Moon #/ command: zerotier:controller: "Create ZeroTier Moon #/ command: zerotier:controller: "Create ZeroTier Moon #/ command: zerotier:controller: "Create ZeroTier Moon #/ command: zerotier:controller: "Create ZeroTier Moon #/ command: zerotier:controller: "Create ZeroTier Moon #/ command: zerotier:controller: "Create ZeroTier Moon #/ command: zerotier:controller: "Create ZeroTier Moon #/ command: zerotier:controller: "Create ZeroTier Moon @DESCRIPTION@ Controller" Controller" Controller" Controller" Controller" Controller" Controller" Controller" Controller" Controller" Controller" Controller"
#/ usage: rerun zerotier:controller  --arg <> [ --comment <>] [ --verbose <>] [ --register <>] [ --requires <>] [ --planet <>] [ --moons <>] [ --public <>] [ --secret <>] [ --port <9993>]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: ARG COMMENT VERBOSE REGISTER REQUIRES PLANET MOONS PUBLIC SECRET PORT

. "$RERUN_MODULE_DIR/lib/functions.sh" "controller" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail -o errtrace

rerun_options_parse "$@"

# Command implementation
# ----------------------
function cleanup {
    PRINT "+H" "Abort. Cleaning up..."
    buildah rm "$NAME"
    rm "$SERVICE"
    PRINT "+X" "Error encountered!"
}
trap cleanup ERR
NAME="zerotier-controller-build"
SERVICE="/etc/systemd/system/podman:zerotier-controller.service"
FROM="debian:stretch-slim"
BIND="/srv/zerotier-controller"
OPTS="-v $BIND:/var/lib/zerotier-one"
mkdir -p "$BIND"
. "$RERUN_MODULES/lib/print.sh"
PRINT "+H" "Pulling source image ($FROM)..."
. "$RERUN_MODULES/lib/buildah.sh"
APT_GET="/usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get -qq"
MKDIR /usr/share/man/man1
MKDIR /usr/share/man/man7
RUN /usr/bin/touch /usr/share/man/man1/sh.distrib.1.gz
RUN cp --remove-destination /usr/share/zoneinfo/UTC /etc/localtime
RUN $APT_GET update
RUN $APT_GET dist-upgrade
RUN $APT_GET --no-install-recommends install curl gnupg dirmngr ca-certificates
SH "curl -Lo - https://www.zerotier.com/misc/contact@zerotier.com.gpg | apt-key add -"
SH "echo 'deb http://download.zerotier.com/debian/stretch stretch main' > /etc/apt/sources.list.d/zerotier.list"
RUN $APT_GET update
RUN $APT_GET install zerotier-one=1.2.12
RUN $APT_GET remove curl gnupg dirmngr ca-certificates
RUN $APT_GET --allow-remove-essential remove sysvinit-utils e2fsprogs e2fslibs tzdata
RUN $APT_GET autoremove
RUN $APT_GET clean
if [ -f "$PLANET" ]
then
    cp "$PLANET" "$BIND/planet"
fi
if [ -d "$MOONS" ]
then
    cp -R "$MOONS" "$BIND"
fi
if [ -f "$PUBLIC" ]
then
    cp "$PUBLIC" "$BIND/identity.public"
fi
if [ -f "$SECRET" ]
then
    cp "$SECRET" "$BIND/identity.secret"
    chmod 0600 "$BIND/identity.secret"
fi
RUN chown -R zerotier-one:zerotier-one /var/lib/zerotier-one
CLEAR /tmp
CLEAR /var/tmp
CLEAR /var/cache
CLEAR /var/log
CLEAR /var/lib/apt/lists
CLEAR /usr/share/man
CLEAR /usr/share/common-licenses
CLEAR /usr/share/doc
CONFIG --entrypoint '["/usr/sbin/zerotier-one"]'
CONFIG --cmd "-p$PORT"
CONFIG --stop-signal TERM
buildah commit --rm --squash "$NAME" containers-storage:zerotier-controller
PRINT "+" "Getting image ID of ZeroTier container..."
IMAGE=$(podman images | grep -F "zerotier-controller " | awk '{print $3}')
PRINT "+" "Generating systemd unit..."
cp "$RERUN_MODULE_DIR/commands/controller/zerotier.service" "$SERVICE"
sed -i "s:__IMAGE__:$IMAGE:g" "$SERVICE"
PRINT "+" "Enabling and starting ZeroTier podman container service..."
systemctl daemon-reload
systemctl enable "podman:zerotier-controller"
systemctl start "podman:zerotier-controller"
PRINT "+" "Checking if ZeroTier podman container service is up..."
systemctl is-active "podman:zerotier-controller"
PRINT "!" "DONE."

exit 113
# Done. Exit with last command exit status.
exit $?

